using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Tracks whether the player is near a water tile generated by <see cref="WorldCreator"/>.
/// Attach to the player (or a manager) and assign the WorldCreator and player transform
/// references in the Inspector.
/// </summary>
public sealed class WaterDetector : MonoBehaviour
{
    [Header("References")]
    [SerializeField] private WorldCreator worldCreator;
    [SerializeField] private Transform playerTransform;

    [Header("Detection")]
    [SerializeField, Min(0f)] private float detectionRadius = 5f;

    public bool IsNearWater { get; private set; }
    public float DistanceToNearestWater { get; private set; } = float.MaxValue;

    /// <summary>Raised whenever the near-water status changes.</summary>
    public event Action<bool> OnWaterProximityChanged;

    private void Update()
    {
        if (playerTransform == null || worldCreator == null)
        {
            return;
        }

        IReadOnlyList<Vector3> waterPositions = worldCreator.WaterTilePositions;
        if (waterPositions == null || waterPositions.Count == 0)
        {
            return;
        }

        float minSqDistance = float.MaxValue;
        Vector3 playerPos = playerTransform.position;

        for (int i = 0; i < waterPositions.Count; i++)
        {
            float sqDist = (playerPos - waterPositions[i]).sqrMagnitude;
            if (sqDist < minSqDistance)
            {
                minSqDistance = sqDist;
            }
        }

        DistanceToNearestWater = Mathf.Sqrt(minSqDistance);

        bool nearWater = minDistance <= detectionRadius;
        if (nearWater != IsNearWater)
        {
            IsNearWater = nearWater;
            OnWaterProximityChanged?.Invoke(IsNearWater);
        }
    }

    private void OnDrawGizmosSelected()
    {
        if (playerTransform == null)
        {
            return;
        }

        Gizmos.color = Color.blue;
        Gizmos.DrawWireSphere(playerTransform.position, detectionRadius);
    }
}
